version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: infra/nginx.Dockerfile
    ports:
      - "80:80"
    depends_on:
      - django
      - nextjs
    restart: unless-stopped

  django:
    build:
      context: ./ie_professors_database
      dockerfile: Dockerfile
    expose:
      - "8000"
    environment:
      - DJANGO_SETTINGS_MODULE=ie_professor_management.settings
    volumes:
      - static_data:/vol/static
      - media_data:/vol/media
    restart: unless-stopped

  nextjs:
    build:
      context: ./ie-professors-frontend
      dockerfile: Dockerfile
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - NEXT_PUBLIC_PROFESSORS_API_SERVICE=
    restart: unless-stopped

volumes:
  static_data:
  media_data: