version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: infra/nginx.Dockerfile
    ports:
      - "80:80"
    depends_on:
      django:
        condition: service_healthy
      nextjs:
        condition: service_healthy
    restart: unless-stopped

  django:
    build:
      context: ./ie_professors_database
      dockerfile: Dockerfile
    expose:
      - "8000"
    environment:
      - DJANGO_SETTINGS_MODULE=ie_professor_management.settings
    volumes:
      - static_data:/vol/static
      - media_data:/vol/media
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped

  nextjs:
    build:
      context: ./ie-professors-frontend
      dockerfile: Dockerfile
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - NEXT_PUBLIC_PROFESSORS_API_SERVICE=
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

volumes:
  static_data:
  media_data: