# Generated by Django 5.2.3 on 2025-06-16 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('course_type', models.CharField(blank=True, choices=[('B', 'Basic'), ('O', 'Optional'), ('C', 'Compulsory')], max_length=2)),
                ('credits', models.FloatField()),
                ('sessions', models.IntegerField()),
                ('area', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Intake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('start_time', models.DateField()),
                ('end_time', models.DateField()),
                ('semester', models.IntegerField(choices=[(0, 'Fall'), (1, 'Spring')])),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('campus', models.CharField(choices=[('Segovia', 'Segovia'), ('Madrid A', 'Madrid A'), ('Madrid B', 'Madrid B')], max_length=50)),
                ('availability', models.CharField(blank=True, choices=[(0, 'Morning'), (1, 'Afternoon')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CourseDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=20)),
                ('campus', models.CharField(max_length=50)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.course')),
                ('intake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_deliveries', to='university.intake')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.professor')),
            ],
        ),
    ]
