# Generated by Django 5.2.3 on 2025-06-16 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intake',
            name='semester',
            field=models.CharField(choices=[('fall', 'Fall'), ('spring', 'Spring')], max_length=10),
        ),
        migrations.AlterField(
            model_name='professor',
            name='availability',
            field=models.CharField(blank=True, choices=[('morning', 'Morning'), ('afternoon', 'Afternoon')], max_length=50),
        ),
    ]
