# Generated by Django 5.2.3 on 2025-06-16 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_alter_intake_semester_alter_professor_availability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursedelivery',
            name='semester',
        ),
        migrations.AlterField(
            model_name='coursedelivery',
            name='campus',
            field=models.CharField(choices=[('Segovia', 'Segovia'), ('Madrid A', 'Madrid A'), ('Madrid B', 'Madrid B')], max_length=50),
        ),
    ]
