# Generated by Django 5.2.3 on 2025-06-17 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_remove_coursedelivery_semester_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('school', models.CharField(choices=[('business', 'Business School'), ('law', 'Law School'), ('sci_and_tech', 'Human Science and Technology School'), ('humanities', 'School of Humanities'), ('econ_glo_affa', 'Politics, Economics and Global Affairs School'), ('arch', 'School of Architecture and Design')], max_length=13)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='university.program'),
        ),
    ]
