# Generated by Django 5.2.3 on 2025-06-18 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0004_program_course_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='minimum_number_of_sessions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='professor',
            name='professor_type',
            field=models.CharField(choices=[('f', 'Faculty'), ('a', 'Adjunct Professor'), ('v', 'Visiting Professor')], default='f', max_length=1),
        ),
    ]
