# Generated by Django 5.2.3 on 2025-06-18 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0005_professor_minimum_number_of_sessions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='area',
        ),
    ]
