# Generated by Django 5.2.3 on 2025-06-18 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0006_remove_course_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursedelivery',
            name='campus',
        ),
        migrations.RemoveField(
            model_name='coursedelivery',
            name='intake',
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('campus', models.CharField(choices=[('Segovia', 'Segovia'), ('Madrid A', 'Madrid A'), ('Madrid B', 'Madrid B')], max_length=50)),
                ('intake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.intake')),
            ],
        ),
        migrations.AddField(
            model_name='coursedelivery',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='university.section'),
        ),
    ]
