# Generated by Django 5.2.3 on 2025-06-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0007_remove_coursedelivery_campus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='course_year',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='professor',
            name='campus',
            field=models.CharField(choices=[('Segovia', 'Segovia'), ('Madrid A', 'Madrid IE Tower')], max_length=50),
        ),
        migrations.AlterField(
            model_name='section',
            name='campus',
            field=models.CharField(choices=[('Segovia', 'Segovia'), ('Madrid A', 'Madrid IE Tower')], max_length=50),
        ),
    ]
