# Generated by Django 5.2.3 on 2025-06-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0008_section_course_year_alter_professor_campus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=1),
        ),
    ]
