# Generated by Django 5.2.3 on 2025-06-26 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0010_alter_section_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='program',
        ),
        migrations.AddField(
            model_name='course',
            name='program',
            field=models.ManyToManyField(null=True, to='university.program'),
        ),
    ]
