# Generated by Django 5.2.3 on 2025-06-26 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0011_remove_course_program_course_program'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='program',
        ),
        migrations.AddField(
            model_name='course',
            name='programs',
            field=models.ManyToManyField(blank=True, null=True, to='university.program'),
        ),
    ]
