# Generated by Django 5.2.3 on 2025-06-26 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0012_remove_course_program_course_programs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('degree_type', models.CharField(choices=[('b', 'Bachelor'), ('m', 'Master'), ('d', 'Doctorate'), ('o', 'Other')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='professor',
            name='birth_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='joined_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='sex',
            field=models.CharField(blank=True, choices=[('H', 'Male'), ('M', 'Female')], max_length=1),
        ),
        migrations.CreateModel(
            name='ProfessorDegree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.degree')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.professor')),
            ],
            options={
                'unique_together': {('professor', 'degree')},
            },
        ),
        migrations.AddField(
            model_name='professor',
            name='degrees',
            field=models.ManyToManyField(through='university.ProfessorDegree', to='university.degree'),
        ),
        migrations.AddField(
            model_name='degree',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.university'),
        ),
        migrations.AlterUniqueTogether(
            name='degree',
            unique_together={('name', 'university')},
        ),
    ]
