# Generated by Django 5.2.3 on 2025-06-26 12:23

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0013_degree_knowledgearea_university_professor_birth_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='corporate_email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='country',
            field=django_countries.fields.CountryField(default='ES', max_length=2),
            preserve_default=False,
        ),
    ]
