# Generated by Django 5.2.3 on 2025-06-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0014_professor_corporate_email_professor_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('atenea_code', models.CharField(max_length=120)),
            ],
        ),
        migrations.AlterModelOptions(
            name='university',
            options={'ordering': ['-name']},
        ),
    ]
