# Generated by Django 5.2.3 on 2025-06-26 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0015_area_alter_university_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KnowledgeArea',
        ),
        migrations.AddField(
            model_name='area',
            name='name_en',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='area',
            name='name_es',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
