# Generated by Django 5.2.3 on 2025-06-26 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0016_delete_knowledgearea_area_name_en_area_name_es'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='university.area'),
        ),
    ]
