# Generated by Django 5.2.3 on 2025-06-26 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0017_course_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.CharField(blank=True, choices=[('BA', 'Basica'), ('OB', 'Obligatoria'), ('OP', 'Optativa'), ('OACT', 'Otras Actividades')], max_length=4),
        ),
    ]
