# Generated by Django 5.2.3 on 2025-06-26 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0018_alter_course_course_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='programs',
            field=models.ManyToManyField(blank=True, to='university.program'),
        ),
    ]
