# Generated by Django 5.2.3 on 2025-06-26 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0019_alter_course_programs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='school',
            field=models.CharField(choices=[('business', 'Business School'), ('law', 'Law School'), ('sci_and_tech', 'Science and Technology School'), ('humanities', 'School of Humanities'), ('econ_glo_affa', 'Politics, Economics and Global Affairs School'), ('arch', 'School of Architecture and Design')], max_length=13),
        ),
    ]
