# Generated by Django 5.2.3 on 2025-07-02 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0020_alter_program_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='campus',
            field=models.CharField(choices=[('Segovia', 'Segovia'), ('Madrid A', 'Madrid IE Tower'), ('Madrid B', 'Madrid Maria de Molina')], max_length=50),
        ),
        migrations.AlterField(
            model_name='section',
            name='campus',
            field=models.CharField(choices=[('Segovia', 'Segovia'), ('Madrid A', 'Madrid IE Tower'), ('Madrid B', 'Madrid Maria de Molina')], max_length=50),
        ),
        migrations.CreateModel(
            name='ProfessorCoursePossibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.course')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.professor')),
            ],
            options={
                'unique_together': {('professor', 'course')},
            },
        ),
        migrations.AddField(
            model_name='professor',
            name='courses',
            field=models.ManyToManyField(through='university.ProfessorCoursePossibility', to='university.course'),
        ),
    ]
