# Generated by Django 5.2.4 on 2025-07-04 09:32

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0021_alter_professor_campus_alter_section_campus_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'verbose_name': 'Area', 'verbose_name_plural': 'Areas'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterModelOptions(
            name='coursedelivery',
            options={'verbose_name': 'Course Delivery', 'verbose_name_plural': 'Course Deliveries'},
        ),
        migrations.AlterModelOptions(
            name='degree',
            options={'verbose_name': 'Degree', 'verbose_name_plural': 'Degrees'},
        ),
        migrations.AlterModelOptions(
            name='intake',
            options={'verbose_name': 'Intake', 'verbose_name_plural': 'Intakes'},
        ),
        migrations.AlterModelOptions(
            name='professor',
            options={'verbose_name': 'Professor', 'verbose_name_plural': 'Professors'},
        ),
        migrations.AlterModelOptions(
            name='professordegree',
            options={'verbose_name': 'Professor Degree', 'verbose_name_plural': 'Professor Degrees'},
        ),
        migrations.AlterModelOptions(
            name='program',
            options={'verbose_name': 'Program', 'verbose_name_plural': 'Programs'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': 'Section', 'verbose_name_plural': 'Sections'},
        ),
        migrations.AlterModelOptions(
            name='university',
            options={'ordering': ['-name'], 'verbose_name': 'University', 'verbose_name_plural': 'Universities'},
        ),
        migrations.AlterField(
            model_name='area',
            name='atenea_code',
            field=models.CharField(max_length=120, verbose_name='Atenea Code'),
        ),
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='area',
            name='name_en',
            field=models.CharField(max_length=120, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='area',
            name='name_es',
            field=models.CharField(max_length=120, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='course',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='university.area', verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=10, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.CharField(blank=True, choices=[('BA', 'Basic'), ('OB', 'Obligatory'), ('OP', 'Optional'), ('OACT', 'Other Activities')], max_length=4, verbose_name='Course Type'),
        ),
        migrations.AlterField(
            model_name='course',
            name='credits',
            field=models.FloatField(verbose_name='Credits'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='course',
            name='programs',
            field=models.ManyToManyField(blank=True, to='university.program', verbose_name='Programs'),
        ),
        migrations.AlterField(
            model_name='course',
            name='sessions',
            field=models.IntegerField(verbose_name='Sessions'),
        ),
        migrations.AlterField(
            model_name='coursedelivery',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.course', verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='coursedelivery',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.professor', verbose_name='Professor'),
        ),
        migrations.AlterField(
            model_name='coursedelivery',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='university.section', verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='degree',
            name='degree_type',
            field=models.CharField(choices=[('b', 'Bachelor'), ('m', 'Master'), ('d', 'Doctorate'), ('o', 'Other')], max_length=1, verbose_name='Degree Type'),
        ),
        migrations.AlterField(
            model_name='degree',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='degree',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.university', verbose_name='University'),
        ),
        migrations.AlterField(
            model_name='intake',
            name='end_time',
            field=models.DateField(verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='intake',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='intake',
            name='semester',
            field=models.CharField(choices=[('fall', 'Fall'), ('spring', 'Spring')], max_length=10, verbose_name='Semester'),
        ),
        migrations.AlterField(
            model_name='intake',
            name='start_time',
            field=models.DateField(verbose_name='Start Time'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='availability',
            field=models.CharField(blank=True, choices=[('morning', 'Morning'), ('afternoon', 'Afternoon')], max_length=50, verbose_name='Availability'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='birth_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Birth Year'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='campus',
            field=models.CharField(choices=[('Segovia', 'Segovia'), ('Madrid A', 'Madrid IE Tower'), ('Madrid B', 'Madrid Maria de Molina')], max_length=50, verbose_name='Campus'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='corporate_email',
            field=models.EmailField(max_length=254, null=True, unique=True, verbose_name='Corporate Email'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='joined_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Joined Year'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='minimum_number_of_sessions',
            field=models.PositiveIntegerField(default=0, verbose_name='Minimum Number of Sessions'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='professor_type',
            field=models.CharField(choices=[('f', 'Faculty'), ('a', 'Adjunct Professor'), ('v', 'Visiting Professor')], default='f', max_length=1, verbose_name='Professor Type'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='sex',
            field=models.CharField(blank=True, choices=[('H', 'Male'), ('M', 'Female')], max_length=1, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='professordegree',
            name='degree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.degree', verbose_name='Degree'),
        ),
        migrations.AlterField(
            model_name='professordegree',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.professor', verbose_name='Professor'),
        ),
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='program',
            name='school',
            field=models.CharField(choices=[('business', 'Business School'), ('law', 'Law School'), ('sci_and_tech', 'Science and Technology School'), ('humanities', 'School of Humanities'), ('econ_glo_affa', 'Politics, Economics and Global Affairs School'), ('arch', 'School of Architecture and Design')], max_length=13, verbose_name='School'),
        ),
        migrations.AlterField(
            model_name='section',
            name='campus',
            field=models.CharField(choices=[('Segovia', 'Segovia'), ('Madrid A', 'Madrid IE Tower'), ('Madrid B', 'Madrid Maria de Molina')], max_length=50, verbose_name='Campus'),
        ),
        migrations.AlterField(
            model_name='section',
            name='course_year',
            field=models.SmallIntegerField(default=1, verbose_name='Course Year'),
        ),
        migrations.AlterField(
            model_name='section',
            name='intake',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.intake', verbose_name='Intake'),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=1, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='university',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
    ]
