# Generated by Django 5.2.4 on 2025-07-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0022_alter_area_options_alter_course_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='last_name',
            field=models.CharField(default='', max_length=120, verbose_name='Last Name'),
            preserve_default=False,
        ),
    ]
