# Generated by Django 5.2.4 on 2025-07-04 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0023_professor_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='course',
            name='name_es',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
    ]
