# Generated by Django 5.2.4 on 2025-07-04 11:33

from django.db import migrations,models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0026_historicalarea_historicalcourse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalcourse",
            name="name_en",
            field=models.CharField(max_length=255, null=True, blank=True),
        ),
        migrations.AddField(
            model_name="historicalcourse",
            name="name_es",
            field=models.CharField(max_length=255, null=True, blank=True),
        ),
    ]
