# Generated by Django 5.2.4 on 2025-07-04 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0027_add_name_translations_to_historicalcourse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='course',
            name='updated_at',
        ),
        migrations.DeleteModel(
            name='HistoricalCourse',
        ),
    ]
