# Generated by Django 5.2.4 on 2025-07-04 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0029_course_created_at_course_updated_at_historicalcourse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='course',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='historicalcourse',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='historicalcourse',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='historicalcourse',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='historicalcourse',
            name='name_es',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
    ]
