# Generated by Django 5.2.4 on 2025-07-04 12:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0030_remove_course_created_at_remove_course_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalprofessor',
            name='campus',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='campus',
        ),
        migrations.AddField(
            model_name='historicalprofessor',
            name='campuses',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Segovia', 'Segovia'), ('Madrid A', 'Madrid IE Tower'), ('Madrid B', 'Madrid Maria de Molina')], max_length=50, verbose_name='Campus'), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='professor',
            name='campuses',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Segovia', 'Segovia'), ('Madrid A', 'Madrid IE Tower'), ('Madrid B', 'Madrid Maria de Molina')], max_length=50, verbose_name='Campus'), blank=True, default=list, size=None),
        ),
    ]
