# Generated by Django 5.2.4 on 2025-07-04 12:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0031_remove_historicalprofessor_campus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalprofessor',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='availability',
        ),
        migrations.AddField(
            model_name='historicalprofessor',
            name='availabilities',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon')], max_length=50, verbose_name='Availability'), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='professor',
            name='availabilities',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon')], max_length=50, verbose_name='Availability'), blank=True, default=list, size=None),
        ),
    ]
