# Generated by Django 5.2.4 on 2025-07-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0032_remove_historicalprofessor_availability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprofessor',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='historicalprofessor',
            name='last_name',
            field=models.CharField(db_index=True, max_length=120, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='historicalprofessor',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='last_name',
            field=models.CharField(db_index=True, max_length=120, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Name'),
        ),
    ]
