# Generated by Django 5.2.4 on 2025-07-04 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0033_alter_historicalprofessor_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='intake',
            options={'ordering': ['-start_time'], 'verbose_name': 'Intake', 'verbose_name_plural': 'Intakes'},
        ),
        migrations.AlterField(
            model_name='historicalintake',
            name='start_time',
            field=models.DateField(db_index=True, verbose_name='Start Time'),
        ),
        migrations.AlterField(
            model_name='intake',
            name='start_time',
            field=models.DateField(db_index=True, verbose_name='Start Time'),
        ),
    ]
