# Generated by Django 5.2.4 on 2025-07-04 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0034_alter_intake_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedelivery',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='university.professor', verbose_name='Professor'),
        ),
    ]
