# Generated by Django 5.2.4 on 2025-07-15 10:28

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0035_alter_coursedelivery_professor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentIntake',
            fields=[
            ],
            options={
                'verbose_name': 'Current Intake',
                'verbose_name_plural': 'Current Intakes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('university.intake',),
        ),
        migrations.AddField(
            model_name='historicalsection',
            name='program',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='university.program', verbose_name='Program'),
        ),
        migrations.AddField(
            model_name='section',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='university.program', verbose_name='Program'),
        ),
        migrations.AlterUniqueTogether(
            name='coursedelivery',
            unique_together={('course', 'section')},
        ),
        migrations.CreateModel(
            name='HistoricalCurrentIntake',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='updated_at')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Name')),
                ('start_time', models.DateField(db_index=True, verbose_name='Start Time')),
                ('end_time', models.DateField(verbose_name='End Time')),
                ('semester', models.CharField(choices=[('fall', 'Fall'), ('spring', 'Spring')], max_length=10, verbose_name='Semester')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Current Intake',
                'verbose_name_plural': 'historical Current Intakes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
