# Generated by Django 5.2.4 on 2025-07-15 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0036_currentintake_historicalsection_program_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('name', 'intake', 'campus', 'course_year', 'program')},
        ),
    ]
