# Generated by Django 5.2.4 on 2025-07-15 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0037_alter_section_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coursedelivery',
            unique_together={('section', 'professor')},
        ),
        migrations.RemoveField(
            model_name='historicalcoursedelivery',
            name='course',
        ),
        migrations.AddField(
            model_name='coursedelivery',
            name='courses',
            field=models.ManyToManyField(to='university.course', verbose_name='Courses'),
        ),
        migrations.RemoveField(
            model_name='coursedelivery',
            name='course',
        ),
    ]
