# Generated by Django 5.2.4 on 2025-07-15 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0038_alter_coursedelivery_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coursedelivery',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='historicalcoursedelivery',
            name='section',
        ),
        migrations.AddField(
            model_name='coursedelivery',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='university.course', verbose_name='Course'),
        ),
        migrations.AddField(
            model_name='coursedelivery',
            name='sections',
            field=models.ManyToManyField(null=True, to='university.section', verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='historicalcoursedelivery',
            name='course',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='university.course', verbose_name='Course'),
        ),
        migrations.RemoveField(
            model_name='coursedelivery',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='coursedelivery',
            name='section',
        ),
    ]
