# Generated by Django 5.2.4 on 2025-07-15 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0039_alter_coursedelivery_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='area',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='historicalarea',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='historicalarea',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='historicalarea',
            name='name_en',
            field=models.CharField(max_length=120, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='historicalarea',
            name='name_es',
            field=models.CharField(max_length=120, null=True, verbose_name='Name'),
        ),
    ]
