# Generated by Django 5.2.4 on 2025-07-15 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0040_remove_area_created_at_remove_area_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedelivery',
            name='sections',
            field=models.ManyToManyField(to='university.section', verbose_name='Section'),
        ),
    ]
