# Generated by Django 5.2.4 on 2025-07-16 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0041_alter_coursedelivery_sections'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['-created_at'], 'verbose_name': 'Section', 'verbose_name_plural': 'Sections'},
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['-created_at'], name='university__created_50b5e0_idx'),
        ),
    ]
