# Generated by Django 5.2.4 on 2025-07-16 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0042_alter_section_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprogram',
            name='code',
            field=models.CharField(db_index=True, max_length=10, null=True, verbose_name='Code'),
        ),
        migrations.AddField(
            model_name='program',
            name='code',
            field=models.CharField(max_length=10, null=True, unique=True, verbose_name='Code'),
        ),
    ]
