# Generated by Django 5.2.4 on 2025-07-22 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0043_historicalprogram_code_program_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalprofessorcoursepossibility',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Course Posibiliti', 'verbose_name_plural': 'historical Course Posibilitis'},
        ),
        migrations.AlterModelOptions(
            name='professorcoursepossibility',
            options={'verbose_name': 'Course Posibiliti'},
        ),
        migrations.RemoveField(
            model_name='historicalprofessor',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='sex',
        ),
        migrations.AddField(
            model_name='historicalprofessor',
            name='accredited',
            field=models.BooleanField(blank=True, null=True, verbose_name='Accredited'),
        ),
        migrations.AddField(
            model_name='historicalprofessor',
            name='gender',
            field=models.CharField(blank=True, choices=[('H', 'Male'), ('M', 'Female')], max_length=1, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='historicalprofessor',
            name='linkedin_profile',
            field=models.URLField(blank=True, null=True, verbose_name='LinkedIn Profile'),
        ),
        migrations.AddField(
            model_name='professor',
            name='accredited',
            field=models.BooleanField(blank=True, null=True, verbose_name='Accredited'),
        ),
        migrations.AddField(
            model_name='professor',
            name='gender',
            field=models.CharField(blank=True, choices=[('H', 'Male'), ('M', 'Female')], max_length=1, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='professor',
            name='linkedin_profile',
            field=models.URLField(blank=True, null=True, verbose_name='LinkedIn Profile'),
        ),
        migrations.AlterField(
            model_name='historicalprofessor',
            name='corporate_email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True, verbose_name='Corporate Email'),
        ),
        migrations.AlterField(
            model_name='historicalprofessor',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, verbose_name='Personal Email'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='corporate_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Corporate Email'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, verbose_name='Personal Email'),
        ),
        migrations.CreateModel(
            name='CourseDeliverySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.coursedelivery')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.section')),
            ],
            options={
                'unique_together': {('course_delivery', 'section')},
            },
        ),
    ]
