# Generated by Django 5.2.4 on 2025-07-22 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0044_alter_historicalprofessorcoursepossibility_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalprofessorcoursepossibility',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Course Possibilitie', 'verbose_name_plural': 'historical Course Possibilities'},
        ),
        migrations.AlterModelOptions(
            name='professorcoursepossibility',
            options={'verbose_name': 'Course Possibilitie'},
        ),
        migrations.RemoveField(
            model_name='area',
            name='atenea_code',
        ),
        migrations.RemoveField(
            model_name='historicalarea',
            name='atenea_code',
        ),
        migrations.AlterField(
            model_name='historicalprofessor',
            name='minimum_number_of_sessions',
            field=models.PositiveIntegerField(default=0, verbose_name='PDP (required number of sessions)'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='minimum_number_of_sessions',
            field=models.PositiveIntegerField(default=0, verbose_name='PDP (required number of sessions)'),
        ),
    ]
