# Generated by Django 5.2.4 on 2025-07-22 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0045_alter_historicalprofessorcoursepossibility_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalintake',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Term/Semester', 'verbose_name_plural': 'historical Intakes'},
        ),
        migrations.AlterModelOptions(
            name='intake',
            options={'ordering': ['-start_time'], 'verbose_name': 'Term/Semester', 'verbose_name_plural': 'Intakes'},
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=10, unique=True, verbose_name='Abbreviation'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.CharField(blank=True, choices=[('BA', 'Basic'), ('OB', 'Obligatory'), ('OP', 'Optional'), ('CA', 'Complementary Activity'), ('EL', 'Electives'), ('RE', 'Regular'), ('OACT', 'Other Activities')], max_length=4, verbose_name='Course Type'),
        ),
        migrations.AlterField(
            model_name='historicalcourse',
            name='code',
            field=models.CharField(db_index=True, max_length=10, verbose_name='Abbreviation'),
        ),
        migrations.AlterField(
            model_name='historicalcourse',
            name='course_type',
            field=models.CharField(blank=True, choices=[('BA', 'Basic'), ('OB', 'Obligatory'), ('OP', 'Optional'), ('CA', 'Complementary Activity'), ('EL', 'Electives'), ('RE', 'Regular'), ('OACT', 'Other Activities')], max_length=4, verbose_name='Course Type'),
        ),
    ]
