# Generated by Django 5.2.4 on 2025-07-22 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0047_joinedacademicyear_historicaljoinedacademicyear_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprogram',
            name='type',
            field=models.CharField(choices=[('ba', 'Bachelors'), ('ma', 'Master')], default='ba', max_length=2, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='program',
            name='type',
            field=models.CharField(choices=[('ba', 'Bachelors'), ('ma', 'Master')], default='ba', max_length=2, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='historicaljoinedacademicyear',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='historicaljoinedacademicyear',
            name='start_date',
            field=models.DateField(verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='joinedacademicyear',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='joinedacademicyear',
            name='start_date',
            field=models.DateField(verbose_name='Start Date'),
        ),
    ]
