# Generated by Django 5.2.4 on 2025-07-23 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0048_historicalprogram_type_program_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalcurrentintake',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='historicalintake',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='intake',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
