# Generated by Django 4.2.23 on 2025-09-03 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0050_historicalprogram_academic_director_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprogram',
            name='years',
            field=models.PositiveIntegerField(default=4, help_text='Duration of the program in years', verbose_name='Years'),
        ),
        migrations.AddField(
            model_name='program',
            name='years',
            field=models.PositiveIntegerField(default=4, help_text='Duration of the program in years', verbose_name='Years'),
        ),
    ]
