# Generated by Django 4.2.23 on 2025-09-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0051_historicalprogram_years_program_years'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsection',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
    ]
