# Generated by Django 4.2.23 on 2025-09-17 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0052_update_section_name_field'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='coursedelivery',
            index=models.Index(fields=['course', 'professor'], name='university__course__1afd69_idx'),
        ),
        migrations.AddIndex(
            model_name='coursedelivery',
            index=models.Index(fields=['professor'], name='university__profess_d2d0b4_idx'),
        ),
        migrations.AddIndex(
            model_name='coursedelivery',
            index=models.Index(fields=['course'], name='university__course__7503fd_idx'),
        ),
        migrations.AddIndex(
            model_name='coursedelivery',
            index=models.Index(fields=['-created_at'], name='university__created_bb8d94_idx'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['intake', 'program'], name='university__intake__03b013_idx'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['program', 'course_year'], name='university__program_735624_idx'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['campus', 'course_year'], name='university__campus_b974d8_idx'),
        ),
    ]
