branch-defaults:
  main:
    environment: Ieuniversitydocker-env
environment-defaults:
  Ieuniversitydocker-env:
    branch: null
    repository: null
global:
  application_name: Ieuniversitydocker
  default_region: eu-north-1
  sc: git
