name: Deploy to AWS Elastic Beanstalk (Single Container)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  AWS_REGION: eu-north-1
  EB_APPLICATION_NAME: Ieuniversitydocker
  EB_ENVIRONMENT_NAME: Ieuniversitydocker-env

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    # 👇 Build deployment package for EB
    - name: Create deployment package
      run: |
        zip -r deploy.zip \
          Dockerfile \
          docker/ \
          ie_professors_database/ \
          ie-professors-frontend/ \
          .ebextensions/ \
          .platform/ \
          --exclude=**/__pycache__/** \
          --exclude=**/node_modules/** \
          --exclude=**/.pytest_cache/** \
          --exclude=**/*.log

    # 👇 Deploy to Elastic Beanstalk
    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v22
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: ${{ env.EB_APPLICATION_NAME }}
        environment_name: ${{ env.EB_ENVIRONMENT_NAME }}
        region: ${{ env.AWS_REGION }}
        version_label: ${{ github.sha }}
        deployment_package: deploy.zip

    # 👇 Set EB environment variables
    - name: Set EB Environment Variables
      run: |
        aws elasticbeanstalk update-environment \
          --application-name ${{ env.EB_APPLICATION_NAME }} \
          --environment-name ${{ env.EB_ENVIRONMENT_NAME }} \
          --option-settings \
            Namespace=aws:elasticbeanstalk:application:environment,OptionName=DJANGO_ALLOWED_HOSTS,Value="${{ secrets.DJANGO_ALLOWED_HOSTS }}" \
            Namespace=aws:elasticbeanstalk:application:environment,OptionName=DJANGO_SECRET_KEY,Value="${{ secrets.DJANGO_SECRET_KEY }}" \
            Namespace=aws:elasticbeanstalk:application:environment,OptionName=DB_NAME,Value="${{ secrets.DB_NAME }}" \
            Namespace=aws:elasticbeanstalk:application:environment,OptionName=DB_USER,Value="${{ secrets.DB_USER }}" \
            Namespace=aws:elasticbeanstalk:application:environment,OptionName=DB_PASSWORD,Value="${{ secrets.DB_PASSWORD }}" \
            Namespace=aws:elasticbeanstalk:application:environment,OptionName=DB_HOST,Value="${{ secrets.DB_HOST }}" \
            Namespace=aws:elasticbeanstalk:application:environment,OptionName=DB_PORT,Value="${{ secrets.DB_PORT }}"

    # 👇 Configure EB Health Check
    - name: Configure EB Health Check
      run: |
        aws elasticbeanstalk update-environment \
          --application-name ${{ env.EB_APPLICATION_NAME }} \
          --environment-name ${{ env.EB_ENVIRONMENT_NAME }} \
          --option-settings \
            Namespace=aws:elasticbeanstalk:healthreporting:system,OptionName=SystemType,Value=enhanced \
            Namespace=aws:elasticbeanstalk:application:environment,OptionName=HEALTHCHECK_URL,Value=/health
